### ISSUE TITLE
Can "iInterface" be set to an arbitrary string from this?

### ISSUE THREAD

**Issue by buzmeg** [xairy/raw-gadget#2]
One of the issues I recently had was that it's not actually possible for any of the current Linux usb gadgets to set "iInterface".  This is wired to a specific value based upon the gadget driver and is not exposed in configFS.  Because of its commonality across all the function drivers, this is a problematic amount of work to fix.

Can this raw-gadget be used to side step that issue?

Thanks.

**Comment by xairy** [comment]
Hi!

Yes, Raw Gadget can do that, but it also can be done with GadgetFS, which is available in most distros.

Thanks!
