### ISSUE TITLE
Out-of-scope: Use inside Android device

### ISSUE THREAD

**Issue by lars18th** [xairy/raw-gadget#3]
Hi @xairy ,

Your RAW GADGET module seems very useful. However, it's quite difficult to use it inside an Android device (without rooting it). Then I ask if you feel it's possible to have some Android API to access to low level gadget functions.

Regards.

**Comment by xairy** [comment]
Hi!

Raw Gadget will most probably make it into the Android common kernels, but it's unlikely it'll be enabled on consumer devices.

Thanks!

**Comment by lars18th** [comment]
Hi @xairy ,

Thank you for your response.
