### ISSUE TITLE
device side resume signal 

### ISSUE THREAD

**Issue by tester58126** [xairy/raw-gadget#62]
usb host : windows amd64 pc
usb hub device : rpi4 usb otg port

simulate usb 2.0 hub device using usb otg port of rpi4

usb hub device is suspended after receiving USB_RAW_EVENT_SUSPEND event after USB enumeration

this is a normal process but i don't know how to generate resume signal to usb host from device side

thank you

**Comment by xairy** [comment]
I believe emulating a USB hub through the Gadget subsystem requires support for this in the UDC hardware and the driver. And looks like only the Aspeed UDCs [allow that](https://www.spinics.net/lists/linux-usb/msg157518.html).

If you manage find any reference to a Raspberry Pi being able to emulate a USB hub, I can try to figure out why it doesn't work with Raw Gadget. But I suspect this is just not supported by the Raspberry Pi's UDC.
