### ISSUE TITLE
On a Raspberry Pi, follow these instructions.

### ISSUE THREAD

**Issue by onlineapps-cloud** [xairy/raw-gadget#63]
hi, you have wrong link in  [these instructions](https://github.com/notro/rpi-source/wiki).
`correct link is:` https://github.com/RPi-Distro/rpi-source
![image](https://github.com/xairy/raw-gadget/assets/69077240/343f1397-3c72-472c-aeb1-d2212522026a)

**Comment by xairy** [comment]
Fixed in 00070af8519313045c8b3ce5bdc121267f5a3a60, thanks!
