### ISSUE TITLE
Building for kernels <4.19

### ISSUE THREAD

**Issue by h3rl** [xairy/raw-gadget#68]
Just a heads up :)
I had the issue where it would not build on my 4.9 kernel because ida_alloc and ida_free was not implemented. The fix was to build on an older version, specifically commit f7cfde4 before the ida functionality was used for raw-gadget. This affects all kernels bellow 4.19 according to this https://elixir.bootlin.com/linux/v4.19.313/source/include/linux/idr.h
Just leaving this for information, maybe update readme?

**Comment by xairy** [comment]
Hi! Yeah, keeping external modules compatible with different kernel versions is a pain. I'll keep this issue open as a reminder to update the readme, thanks for the info!
