### ISSUE TITLE
adding new  SBC compatibility

### ISSUE THREAD

**Issue by daytona675** [xairy/raw-gadget#75]
Hi xairy, 
thanks for you tool and your work.
I would like to inform you that I've tested raw_gadget on my new RPI5 8Go.
It work fine ! 
So you can add it in your readme on the section board compatibility.
Thanks again for your work ! 
K.R

**Comment by daytona675** [comment]
for this section:USB Device Controllers ;)

**Comment by xairy** [comment]
Hi! That's awesome, thank you for testing! Could you tell me the kernel version that you used and the names of the UDC device and driver?

**Comment by daytona675** [comment]
Hi xairy,
for kernel version i've tested:
6.8.0-1007-raspi 
6.5.x branch
6.2x branch but I'm not sure for this one

For UDC device and driver:
I'm using this driver for both device and driver:
cat /sys/class/udc/1000480000.usb/uevent 
USB_UDC_NAME=1000480000.usb
K.R
