### ISSUE TITLE
technical query about Raw_gadget

### ISSUE THREAD

**Issue by daytona675** [xairy/raw-gadget#76]
Hi Xairy,
i would like to know if it's possible via taw_gadget and USB command (set for example) to talk with the PCIe bus ? 
In some case the USB3 port is not realy an usb but il could be a pcie devica that talk usb.(this is the case for example for the RPI5 or on Laptop).
So if i tune the usb query/set commande, is it could be possible or I dream ? 

This is an example of udevadm monitor:
UDEV  [1181.602893] bind     /devices/platform/axi/1000120000.pcie/1f00200000.usb/xhci-hcd.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:04D9:0183.000A (hid)
this is my usb keyboard and you have a driver: 1f00200000.usb => is it possible to use it with raw_gadget  first? (it's not an OTG usb port)
And of course talk to pcie in second with the 1000120000.pcie driver.

K.R

**Comment by xairy** [comment]
Hi! No, it's not possible to use Raw Gadget for PCIe emulation. I'm not even sure it's possible without using specialized hardware, like the kind used for [pcileech](https://github.com/ufrisk/pcileech). Thanks!
